---
- name: Ejecuta script borra_productos.sh
  hosts: all
  tasks:     
    - name: Ejecuta script
      #command: sh /tmp/prueba.sh
      ansible.builtin.shell: "sh borra_productos.sh"
      args:
        chdir: "/home/mareguera/ansible/bin"
