---
- name: Ejecuta script
  hosts: all
  tasks:
    - name: Dame estado del objeto
      ansible.builtin.stat:
        path: "/tmp/prueba.sh"
      register: sym

    - name: Print a debug message
      ansible.builtin.debug:
        msg: "islnk isn't defined (path doesn't exist)"
      when: sym.stat.islnk is not defined
      
    - name: Print a debug message
      ansible.builtin.debug:
        msg: "islnk is defined (path must exist)"
      when: sym.stat.islnk is defined

    - name: Print a debug message
      ansible.builtin.debug:
        msg: "Path exists and is a symlink"
      when: sym.stat.islnk is defined and sym.stat.islnk

    - name: Print a debug message
      ansible.builtin.debug:
        msg: "Path exists and isn't a symlink"
      when: sym.stat.islnk is defined and sym.stat.islnk == False
      
    - name: Ejecuta script
      #command: sh /tmp/prueba.sh
      ansible.builtin.shell: "sh prueba.sh"
      args:
        chdir: "/tmp/"
