---
- name: Ejecuta script en localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Dame estado del objeto
      ansible.builtin.stat:
        path: "{{ path_file }}"
      register: sym

    - name: Print a debug message
      ansible.builtin.debug:
        msg: "{{ path_file }} islnk isn't defined (path doesn't exist)"
      when: sym.stat.islnk is not defined
      
    - name: Print a debug message
      ansible.builtin.debug:
        msg: "{{ path_file }} islnk is defined (path must exist)"
      when: sym.stat.islnk is defined

    - name: Print a debug message
      ansible.builtin.debug:
        msg: "{{ path_file }} Path exists and is a symlink"
      when: sym.stat.islnk is defined and sym.stat.islnk

    - name: Print a debug message
      ansible.builtin.debug:
        msg: "{{ path_file }} Path exists and isn't a symlink"
      when: sym.stat.islnk is defined and sym.stat.islnk == False
  
    - name: Ejecuta script en localhost
      ansible.builtin.shell: "ls -al"
      args:
        chdir: "/"
      #command: sh /tmp/prueba.sh
