---
- name: Ejecuta script provision_apache.sh
  hosts: all
  tasks:     
    - name: Ejecuta script
      #command: sh /tmp/prueba.sh
      ansible.builtin.shell: "sh provision_apache.sh"
      args:
        chdir: "/home/mareguera/ansible/bin"
